[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[project]
name = "bitget-api"
version = "1.0.0"
description = "A Python client for the Bitget API with comprehensive position management"
authors = [
    {name = "Tentoxa"}
]
requires-python = ">=3.7"
